param(
  [Parameter(Mandatory=$true)]
  [string]$ExtensionId,

  [ValidateSet("Chrome", "Edge", "All")]
  [string]$Browser = "Chrome",

  [string]$InstallDir = "$env:LOCALAPPDATA\AblesciPdfWatcherPrivate"
)

$ErrorActionPreference = "Stop"

$HostName = "com.ablesci.pdf_watcher_private"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$InstallDir = [System.IO.Path]::GetFullPath($InstallDir)
$PrebuiltExe = Join-Path $RepoRoot "native-helper\bin\windows-amd64\ablesci_pdf_helper.exe"
$SourceGoDir = Join-Path $RepoRoot "native-helper"
$MarkerFileName = ".ablesci_pdf_watcher_private.install.json"

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

$TargetExe = Join-Path $InstallDir "ablesci_pdf_helper.exe"
$TargetExe = [System.IO.Path]::GetFullPath($TargetExe)

if (Test-Path $PrebuiltExe) {
  Copy-Item $PrebuiltExe $TargetExe -Force
} else {
  if (!(Get-Command go -ErrorAction SilentlyContinue)) {
    throw "Go was not found. Install Go first, then rerun install_host.ps1."
  }
  Push-Location $SourceGoDir
  try {
    $env:GOOS = "windows"
    $env:GOARCH = "amd64"
    $env:CGO_ENABLED = "0"
    go build -trimpath -ldflags "-s -w" -o $TargetExe .
  } finally {
    Pop-Location
  }
}

$ManifestPath = Join-Path $InstallDir "$HostName.json"
$ManifestPath = [System.IO.Path]::GetFullPath($ManifestPath)
$AllowedOrigin = "chrome-extension://$ExtensionId/"
$ExistingOrigins = @()
if (Test-Path $ManifestPath) {
  try {
    $ExistingManifest = Get-Content -Raw $ManifestPath | ConvertFrom-Json
    if ($ExistingManifest.allowed_origins) {
      $ExistingOrigins = @($ExistingManifest.allowed_origins)
    }
  } catch {
    $ExistingOrigins = @()
  }
}
$AllowedOrigins = @($ExistingOrigins + $AllowedOrigin | Where-Object { $_ } | Sort-Object -Unique)

$manifest = [ordered]@{
  name = $HostName
  description = "Ablesci PDF Watcher Private Native Helper"
  path = $TargetExe
  type = "stdio"
  allowed_origins = $AllowedOrigins
}

$manifest | ConvertTo-Json -Depth 5 | Set-Content -Path $ManifestPath -Encoding UTF8

$MarkerPath = Join-Path $InstallDir $MarkerFileName
$Marker = [ordered]@{
  host_name = $HostName
  install_dir = $InstallDir
  helper_exe = [System.IO.Path]::GetFileName($TargetExe)
  manifest = [System.IO.Path]::GetFileName($ManifestPath)
  installed_at = (Get-Date).ToString("s")
}
$Marker | ConvertTo-Json -Depth 4 | Set-Content -Path $MarkerPath -Encoding UTF8

# Copy notification icon alongside the helper binary
$NotifyIconSrc = Join-Path $RepoRoot "extension\icons\icon48.png"
if (Test-Path $NotifyIconSrc) {
  $NotifyIconDst = Join-Path $InstallDir "icon48.png"
  Copy-Item -LiteralPath $NotifyIconSrc -Destination $NotifyIconDst -Force
  Write-Host "Copied notify icon: $NotifyIconDst"
}

# Copy .ico for Start Menu shortcut (generated by build_helper.ps1)
$IcoSrc = Join-Path $RepoRoot "native-helper\bin\windows-amd64\icon.ico"
if (Test-Path $IcoSrc) {
  $IcoDst = Join-Path $InstallDir "icon.ico"
  Copy-Item -LiteralPath $IcoSrc -Destination $IcoDst -Force
  Write-Host "Copied .ico: $IcoDst"
}

# Register Start Menu shortcut with AppUserModelID so Windows notification
# shows the plugin icon in the top-left source area.
$ShortcutCode = @"
using System;
using System.Runtime.InteropServices;
using System.Text;

[ComImport, Guid("00021401-0000-0000-C000-000000000046")]
public class ShellLink {}

[ComImport, Guid("000214F9-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IShellLinkW {
    void GetPath(StringBuilder sb, int cch, IntPtr pfd, uint fFlags);
    IntPtr GetIDList();
    void SetIDList(IntPtr pidl);
    void GetDescription(StringBuilder sb, int cch);
    void SetDescription([MarshalAs(UnmanagedType.LPWStr)] string pszName);
    void GetWorkingDirectory(StringBuilder sb, int cch);
    void SetWorkingDirectory([MarshalAs(UnmanagedType.LPWStr)] string pszDir);
    void GetArguments(StringBuilder sb, int cch);
    void SetArguments([MarshalAs(UnmanagedType.LPWStr)] string pszArgs);
    ushort GetHotKey();
    void SetHotKey(ushort wHotKey);
    uint GetShowCmd();
    void SetShowCmd(uint iShowCmd);
    void GetIconLocation(StringBuilder sb, int cch, out int piIcon);
    void SetIconLocation([MarshalAs(UnmanagedType.LPWStr)] string pszIconPath, int iIcon);
    void SetRelativePath([MarshalAs(UnmanagedType.LPWStr)] string pszPathRel, uint dwReserved);
    void Resolve(IntPtr hwnd, uint fFlags);
    void SetPath([MarshalAs(UnmanagedType.LPWStr)] string pszFile);
}

[ComImport, Guid("0000010B-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IPersistFile {
    void GetCurFile([Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder pszFile);
    [PreserveSig] int IsDirty();
    void Load([MarshalAs(UnmanagedType.LPWStr)] string pszFileName, uint dwMode);
    void Save([MarshalAs(UnmanagedType.LPWStr)] string pszFileName, [MarshalAs(UnmanagedType.Bool)] bool fRemember);
    void SaveCompleted([MarshalAs(UnmanagedType.LPWStr)] string pszFileName);
}

[StructLayout(LayoutKind.Sequential)]
public struct PROPERTYKEY {
    public Guid fmtid;
    public uint pid;
}

[ComImport, Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IPropertyStore {
    [PreserveSig] int GetCount(out uint cProps);
    [PreserveSig] int GetAt(uint iProp, out PROPERTYKEY pkey);
    [PreserveSig] int GetValue(ref PROPERTYKEY key, out IntPtr pv); // simplified
    [PreserveSig] int SetValue(ref PROPERTYKEY key, ref PROPVARIANT pv);
    [PreserveSig] int Commit();
}

[StructLayout(LayoutKind.Sequential)]
public struct PROPVARIANT {
    public ushort vt;
    ushort wReserved1;
    ushort wReserved2;
    ushort wReserved3;
    public IntPtr ptrVal;
}

public static class ShortcutManager {
    public static void Create(string lnkPath, string targetPath, string iconPath, string appId) {
        var link = (IShellLinkW)new ShellLink();
        link.SetPath(targetPath);
        if (!string.IsNullOrEmpty(iconPath)) {
            link.SetIconLocation(iconPath, 0);
        }
        var store = (IPropertyStore)link;
        var key = new PROPERTYKEY {
            fmtid = new Guid("9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3"),
            pid = 5  // PKEY_AppUserModel_ID
        };
        var pv = new PROPVARIANT();
        pv.vt = 31;  // VT_LPWSTR
        pv.ptrVal = Marshal.StringToCoTaskMemUni(appId);
        store.SetValue(ref key, ref pv);
        store.Commit();
        Marshal.FreeCoTaskMem(pv.ptrVal);
        var file = (IPersistFile)link;
        var dir = System.IO.Path.GetDirectoryName(lnkPath);
        if (!System.IO.Directory.Exists(dir)) {
            System.IO.Directory.CreateDirectory(dir);
        }
        file.Save(lnkPath, true);
    }
}
"@

$AppIdForShortcut = "AblesciPDFUploader"
$ShortcutName = "Ablesci PDF Uploader"
$StartMenuPrograms = [Environment]::GetFolderPath('StartMenu') + "\Programs"
$ShortcutDir = Join-Path $StartMenuPrograms "Ablesci PDF Uploader"
$ShortcutPath = Join-Path $ShortcutDir "$ShortcutName.lnk"
$ShortcutIcon = if (Test-Path $IcoDst) { $IcoDst } else { $TargetExe + ",0" }

try {
  Add-Type -TypeDefinition $ShortcutCode -ReferencedAssemblies "System.Runtime.InteropServices"
  [ShortcutManager]::Create($ShortcutPath, $TargetExe, $ShortcutIcon, $AppIdForShortcut)
  Write-Host "Start Menu shortcut created: $ShortcutPath"
  Write-Host "  AppUserModelID = $AppIdForShortcut"
  Write-Host "  Icon = $ShortcutIcon"
} catch {
  Write-Warning "Failed to create Start Menu shortcut: $_"
}

$Browsers = if ($Browser -eq "All") { @("Chrome", "Edge") } else { @($Browser) }
foreach ($BrowserName in $Browsers) {
  if ($BrowserName -eq "Chrome") {
    $RegKey = "HKCU\Software\Google\Chrome\NativeMessagingHosts\$HostName"
  } else {
    $RegKey = "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\$HostName"
  }
  & reg.exe add $RegKey /ve /t REG_SZ /d $ManifestPath /f | Out-Null
  Write-Host "Registry entry written: $RegKey"
}

Write-Host "Native host installed."
Write-Host "Host name: $HostName"
Write-Host "Manifest : $ManifestPath"
Write-Host "Helper   : $TargetExe"
Write-Host "Allowed origins: $($AllowedOrigins -join ', ')"
Write-Host "You can now click Test Native Helper in the extension options page."
